---
abstract: "Detect full \"Internet\" (HTTP) access using Microsoft NCSI"
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTTP::Online
name: HTTP-Online
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::Tiny: 0.019
  Test::More: 0.42
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/HTTP-Online
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/HTTP-Online
version: 0.02
